# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_info', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=200)),
                ('modify_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.Entity'),
        ),
    ]
